name: angular_chartjs
description: Angular example using Chartjs
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.20
  browser: ^0.10.0
  js: ^0.6.0
  dart_to_js_script_rewriter: ^1.0.1
  chartjs:
    path: ../../
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
